name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # 노드 설치
      - name: setting Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      
      - name: Cache
        uses: actions/cache@v3.0.2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
    
      # cache 없을때(node_modules 변경될 떄)만 설치
      - name: install dependency
        if: steps.cache.output.cache-hit != true
        run: npm install
        
      - run: npm run lint
        if: ${{ always() }}
        
      - run: npm run test
        if: ${{ always() }}

      - name: send slack message when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: send slack message when completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
        
